# Generated by Django 2.1.10 on 2019-09-22 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190922_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.ImageField(null=True, upload_to='blog/img/Y/m/d/', verbose_name='图片'),
        ),
    ]
