# Generated by Django 2.1.10 on 2019-09-22 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='sex',
            field=models.CharField(choices=[('男', 'M'), ('女', 'W')], default='男', max_length=4, verbose_name='性别'),
        ),
    ]
